name: client_data
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

  #Firebase
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1

  provider: ^4.3.2+1
  cloud_firestore: ^0.14.4
  firebase_storage: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/lp_image.png
    - assets/images/client.jpg
    - assets/images/profile.jpg
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf